'use strict';
(()=>{
const $=s=>document.querySelector(s),a=$('#a-audio');let tracks=[],current=-1,group='전체',lastStamp=0;
const read=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},save=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}};
let heard=new Set(read('stp-a-heard',[])),last=read('stp-a-last',null);
const escape=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=s=>Math.floor(s/60)+':'+String(s%60).padStart(2,'0');
function render(){const q=$('#a-search').value.trim().toLowerCase(),items=tracks.filter(t=>(group==='전체'||t.group===group)&&(t.title+t.text+t.location).toLowerCase().includes(q));$('#a-cards').innerHTML=items.map(t=>{let i=tracks.indexOf(t);return `<article class="a-card ${current===i?'playing':''}"><button class="a-card-main" data-play="${i}"><span class="a-meta">${t.id} · ${t.group} · ${fmt(t.duration)} ${heard.has(t.id)?'· ✓ 들었어요':''}</span><strong>${escape(t.title)}</strong><span class="a-location">${escape(t.location)}</span></button><div class="a-card-actions"><button data-play="${i}">${current===i&&!a.paused?'Ⅱ 일시정지':'▶ 듣기'}</button><button data-read="${i}">해설 보기</button><a href="${t.audio}" download="${t.id}_${escape(t.title)}.mp3">MP3 저장 ↓</a></div></article>`}).join('');$('#a-empty').hidden=items.length>0;$('#a-progress').textContent=`${heard.size} / ${tracks.length}개 들었어요`;document.querySelectorAll('[data-inline-play]').forEach(b=>{const i=Number(b.dataset.inlinePlay);b.textContent=current===i&&!a.paused?'Ⅱ 일시정지':'▶ 해설 듣기'});$('#a-prev').disabled=current<=0;$('#a-next').disabled=current>=tracks.length-1}
function failed(){$('#a-error').hidden=false}
async function play(i,time){if(i<0||i>=tracks.length)return;$('#a-player').hidden=false;document.body.classList.add('a-open');$('#a-error').hidden=true;if(i===current&&time===undefined){if(a.paused){try{await a.play()}catch{failed()}}else a.pause();return}current=i;const t=tracks[i];a.src=t.audio;a.playbackRate=Number($('#a-speed').value);if(time)a.currentTime=time;$('#a-title').textContent=t.title;$('#a-download').href=t.audio;$('#a-download').download=t.id+'_'+t.title+'.mp3';save('stp-a-last',{id:t.id,time:time||0});if('mediaSession'in navigator&&'MediaMetadata'in window)navigator.mediaSession.metadata=new MediaMetadata({title:t.title,artist:'성 베드로 가족 오디오 가이드'});render();try{await a.play()}catch{failed()}}
function show(i){const t=tracks[i];if(!t)return;$('#a-dialog-title').textContent=t.title;$('#a-dialog-text').textContent=t.text;$('#a-dialog-tip').textContent=t.tip;$('#a-dialog').showModal()}
$('#a-cards').onclick=e=>{const b=e.target.closest('[data-play]'),r=e.target.closest('[data-read]');if(b)play(+b.dataset.play);if(r)show(+r.dataset.read)};
$('#a-filters').onclick=e=>{const b=e.target.closest('[data-group]');if(!b)return;group=b.dataset.group;document.querySelectorAll('#a-filters button').forEach(x=>x.classList.toggle('selected',x===b));render()};$('#a-search').oninput=render;$('#a-start').onclick=()=>play(0,0);$('#a-prev').onclick=()=>play(current-1,0);$('#a-next').onclick=()=>play(current+1,0);$('#a-back').onclick=()=>a.currentTime=Math.max(0,a.currentTime-10);$('#a-forward').onclick=()=>{if(Number.isFinite(a.duration))a.currentTime=Math.min(a.duration,a.currentTime+10)};$('#a-speed').onchange=e=>a.playbackRate=+e.target.value;$('#a-close').onclick=()=>{a.pause();$('#a-player').hidden=true;document.body.classList.remove('a-open')};$('#a-read').onclick=()=>show(current);$('#a-dialog-close').onclick=()=>$('#a-dialog').close();
a.onplay=render;a.onpause=render;a.onerror=failed;a.ontimeupdate=()=>{if(current>=0&&Date.now()-lastStamp>2000){save('stp-a-last',{id:tracks[current].id,time:a.currentTime});lastStamp=Date.now()}};a.onended=()=>{heard.add(tracks[current].id);save('stp-a-heard',[...heard]);save('stp-a-last',{id:tracks[current].id,time:0});render();if($('#a-auto').checked&&current<tracks.length-1)play(current+1,0)};
function inline(el,i){if(!el)return;const row=document.createElement('div');row.className='a-inline';row.innerHTML=`<button data-inline-play="${i}">▶ 해설 듣기</button><a href="${tracks[i].audio}" download="${tracks[i].id}_${escape(tracks[i].title)}.mp3">MP3 저장 ↓</a>`;row.querySelector('button').onclick=()=>play(i);el.append(row)}
fetch('data.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(t=>{tracks=t;heard=new Set([...heard].filter(id=>tracks.some(t=>t.id===id)));document.querySelectorAll('#square .stop').forEach((el,i)=>inline(el,i));document.querySelectorAll('section[aria-labelledby="h-dome"] > ol.steps > li').forEach((el,i)=>inline(el,i+3));document.querySelectorAll('#tour .stop').forEach((el,i)=>inline(el,i+7));const heads=[...document.querySelectorAll('#tour .subhead')];inline(heads[0]?.nextElementSibling,18);inline(heads[1]?.nextElementSibling?.parentElement?heads[1]:null,19);render();if(last&&tracks.some(t=>t.id===last.id)){$('#a-resume').hidden=false;$('#a-resume').onclick=()=>play(tracks.findIndex(t=>t.id===last.id),last.time||0)}}).catch(()=>{$('#a-empty').hidden=false;$('#a-empty').textContent='음성 목록을 불러오지 못했습니다. 인터넷 연결 후 새로고침해 주세요.'});
})();
